package de.variantsync.repository;

import de.variantsync.subjects.VariabilityCommit;

import java.nio.file.Path;

/**
 * Repository containing variability data extracted from an ISPLRepository.
 * Each commit in this repository is associated to a commit from the ISPLRepository.
 * In each commit, the feature model and meta data on presence conditions of the product line at the corresponding
 * commit in the ISPLRepository can be found.
 */
public interface IVariabilityRepository extends IRepository<VariabilityCommit> {
    /**
     * @return A history of commits that can be analysed for its evolution of variability.
     *         This effectively filters commits for which variability information could not be extracted.
     */
    VariabilityHistory getCommitSequencesForEvolutionStudy();

    /**
     * @return Path on disk to the feature model file of the currently checked out commit.
     *         Null, if there is no such file.
     */
    Path getFeatureModelFile();

    /**
     * @return Path on disk to the variability file of the currently checked out commit, that was generated by
     *         KernelHaven. Null, if there is no such file.
     */
    Path getVariabilityFile();
}
